name: Deploy mkdocs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          python -m pip install mkdocs-material mkdocstrings mkdocs-minify-plugin
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
        
      - name: Deploy with MkDocs
        run: mkdocs gh-deploy
