name: Deploy mkdocs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install flake8 pytest
          python -m pip install mkdocs-material==7.2.1 mkdocstrings==0.15.2 mkdocs-minify-plugin
          
          
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
        
      - name: Deploy with MkDocs
        run: mkdocs gh-deploy
